#!/usr/bin/env fish
set argc (count $argv)
mkdir -p ~/.config/fish
cd ~/.config
git clone git@github.com:wieczorek1990/fish-config.git
if test argc -eq 0
  cp -r fish fish.bak
end
cp -rf fish-config/{.,}* fish/
if test argc -gt 0; and test argv[1] == '-f'
  rm -rf fish-config
end
